### ISSUE TITLE
Strange soil minetweaker issue

### ISSUE THREAD

**Issue by ubermentat** [InfinityRaider/AgriCraft#163]
Latest version of AgriCraft, forge 1291.

Using the Soil.set method as shown on the wiki page results in the following being posted 11 times in the forge log:

`ERROR: Error when trying to set soil: maximum should he higher than minimum`

As near as I can tell from both NEI and the minetweaker log, this doesn't affect the recipes in any way, as they still load just fine.

**Comment by ubermentat** [comment]
Additional info: Further inspection of the minetweaker log file indicates that this error only triggers when using Soil.set for netherwart and the default AgriCraft resource crops (nitorwart and the ore seeds). The error message triggers regardless of what the soil is set to.

**Comment by InfinityRaider** [comment]
Thats to do with brightness, if you set the brightness range like [a-b], then obviously b should be higher than a, it checks for that.
I just noticed there is a derp in the code when setting brightness flaws: https://github.com/InfinityRaider/AgriCraft/blob/master/src/main/java/com/InfinityRaider/AgriCraft/compatibility/minetweaker/Growing.java#L263

That should be "Error when trying to set brightness" instead of "soil". My apologies

**Comment by ubermentat** [comment]
Well in that case, there's still some code weirdness going on. If I use `Brightness.set(<minecraft:nether_wart>, 8, 160;` (for example) I still get that error, even though 8 is definitely less than 16.

**Comment by InfinityRaider** [comment]
Okay seems I switched up the error message, lower and upper bound are inclusive, and should be in the following interval: [0, 16[.
So [min, max] where min>=0, max<16 and min<max

**Comment by ubermentat** [comment]
Changing 16 to 15 fixed the issue. Thanks!
