### ISSUE TITLE
Suggestion: More ic2-ish behavior when mutating

### ISSUE THREAD

**Issue by BBoldt** [InfinityRaider/AgriCraft#177]
So in IC2, mutations can happen despite what block is below. You only need the correct block below in order for the plant to actually mature. I just think this might be interesting to have as a feature. It can add more challenge if you have multiple crops with the same mutations that require different blocks below.

**Comment by InfinityRaider** [comment]
Yes, but it wouldn't make sense, you can't plant a seed where it can not grow, how would a plant that can't grow/be planted in a certain spot sprout there?

**Comment by Fuhrmaaj** [comment]
Do you mean in minecraft or in reality? 

This is how the crops work in IC2 and it can help make crop mutations less predictable if the mod pack maker prefers. 

An example of this in your garden is trying to grow an amaryllis in sand. If you put the bulb in sand, it might grow for a period but won't last long because sand can't keep nutrients well and the plant will starve. Once you transplant the amaryllis to soil, it will receive proper nutrition and flourish.

Having this as an option would be handy for the ore plants. They can sit in dirt, but won't grow until the proper ore is placed below. So if you mutate the plant then you might have to experiment with various ore blocks until it advances in growth stages.

**Comment by InfinityRaider** [comment]
Well I have rewritten it many times and I'm not going to bother, I like it as it is so it will stay like that, I'm sorry.
