### ISSUE TITLE
Seed Analyzer Disconnecting Client

### ISSUE THREAD

**Issue by felda** [InfinityRaider/AgriCraft#196]
agricraft-1.7.10-1.3.1
forge-1.7.10-10.13.3.1387-1.7.10-universal
modpack:  Agrarian Skies 2

http://pastebin.com/5HB50MaZ

After entering  a seed or stack of seeds into the analyzer it will sometimes disconnect a player or players.  Sometimes one player will enter a seed in the analyzer and another player will be disconnected.  The server is hosted locally on my computer (dedicated server) and the friend connects over the Internet and it happens to both of us. The fml-server-latest.log shows no errors.

This shows in the latest.log on disconnect, but I'm not sure if it is relevant:  
14:04:59] [Server thread/INFO]: felda lost connection: TextComponent{text='Disconnected', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}

**Comment by InfinityRaider** [comment]
Hmm, I'm suspecting there's a journal in the analyzers? I think this issue is caused by the NBT getting corrupted, I'll see if I can figure out why and how to fix it.
I'm not sure if it is related but there was an issue in the code where the analyzer would sync between server and client each tick while analyzing, this has been fixed and I'll wait with investigating this issue until I release 1.4 and this issue still persists.
For now, removing the journal from the seed analyzer should stop the disconnects from occurring.

**Comment by kane-thornwyrd** [comment]
I subscribe, same issue here, except the server is on a dedicated host in a data-center. Agrarian Skies 1.1.1 to look up which version of AgriCraft it is.

**Comment by InfinityRaider** [comment]
Can you look at the NBT tag of your journal with an NBT-editor?

**Comment by kane-thornwyrd** [comment]
Do you have a NBT-Editor to advise ? I never used one ¬¬'

**Comment by InfinityRaider** [comment]
jaquadro made one:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-tools/1262665-nbtexplorer-nbt-editor-for-windows-and-mac

**Comment by Tarig0** [comment]
Little more information to add to these issues. The NBT load error seems to be coming from the tileentity. I crash while scanning nether wart even if I close the gui.

**Comment by Tarig0** [comment]
looking at the code and experimenting I belive the offending code is contained in the following lines

https://github.com/InfinityRaider/AgriCraft/blob/master/src/main/java/com/InfinityRaider/AgriCraft/tileentity/TileEntitySeedAnalyzer.java#L146-L147

This is due to the fact that the error resolves it self if you remove the journal. And the Journal already has the seed type analyzed, so all the previous if statements should not have fired.

**Comment by Tarig0** [comment]
Another note this error occurs when there is more than one seed in the journal

**Comment by Tarig0** [comment]
I am able to reproduce the bug when I 

1. analyze an invar seed (random pick) 
2. analyze a nether wart
3. analyze a nether wart (bang)

**Comment by InfinityRaider** [comment]
Maybe, thanks for these pointers, I'll try to reproduce this, but first, on what version did you test this (1.3.1 or a self compiled 1.4)?

**Comment by Tarig0** [comment]
Agrarian skies 1.3.1

**Comment by InfinityRaider** [comment]
Can anyone confirm if this still happens in 1.4 or not?

**Comment by kane-thornwyrd** [comment]
I don't reproduce this issue in my modpack. (Stranded Strained)

**Comment by InfinityRaider** [comment]
I will close this then due to lack of response and since I'm failing to reproduce it as well
