### ISSUE TITLE
[1.4.0] Server Crash when right clicking a fully grown Pneumaticcraft Crop

### ISSUE THREAD

**Issue by Xiaminou** [InfinityRaider/AgriCraft#249]
Server crashed when I right clicked a fully grown 10/10/10 Helium Seed. Breaking full grown Helium Seeds crops while breeding them however did not cause a crash.

Crash Report: http://pastebin.com/F1p5BSau

Edit: No crash when right clicking a fully grown Pneumaticcraft Seed Crop with only Agricraft/Pneumaticcraft installed. (Tested in SSP, no dedicated Server invovled in this one)

**Comment by InfinityRaider** [comment]
This will only crash in SMP because of missing @SideOnly(Side.CLIENT) annotations in PneumaticCraft's classes (see also #234). I made a pr to add but apparently I also overlooked some methods.
MineMaarten told me that the pneumaticcraft crops are deprecated, so I won't bother with this anymore.
Simply disable PneumaticCraft support in the config (as of the next version).
