### ISSUE TITLE
Pneumaticcraft On Dedicated Server

### ISSUE THREAD

**Issue by Mattabase** [InfinityRaider/AgriCraft#258]
http://pastebin.com/NrAxrysV

**Comment by InfinityRaider** [comment]
This is because of mising @SideOnly(Side.CLIENT) annotations in the PneumaticCraft classes, I made a PR to add them, which was merged, however I seem to have forgotten a few. Either go to MineMaarten and ask him to add them or disable PneumaticCraft support.
However he told me the plants are deprecated and will be removed soon so I won't bother with fixing it and I'll be dropping support soon as a result.
