### ISSUE TITLE
[Suggestion] Add way to plant crops automatically.

### ISSUE THREAD

**Issue by OneEyeMaker** [InfinityRaider/AgriCraft#377]
Firtly, great thanks for this mod!
Secondly, I have a suggestion. Please, add a way to automatically place crop sticks in world and plant crops. 
For example, I want to create wheat field (using AgriCraft) of size 25x25. And harvest all crops by Harvester from MFR. To plant all crops now I need click 625 times with crops sticks and 625 times with crops (It's very boring and takes long time). 
Please, create machine for that task, or add ability for Planter (from MFR) to place crop sticks, crossed sticks and plant crops on it.

Now I can't find solution for this task: any fillers don't work, because (as I understand) crop sticks and crops, planted on it are Tile Entities.

P. S. Sorry for my English. I'm from Russia.

**Comment by RlonRyan** [comment]
I think that automating the placement of all those crops is just asking for a gigantic field of weeds, as even if you were able to plant the crops with seeds at the same time, there is always the chance that one crop would somehow miss getting a seed, and from there it all goes to well... weeds.

**Comment by InfinityRaider** [comment]
Thanks for the suggestion, however automation should be for a job that has to be done multiple times in my opinion. Once you put a set of crop sticks down, you should never have to do that again. The only repetitive task after this is harvesting, and that's why that can be automated by "magic blocks" such as the MFR harvester. Automatic planting of crop sticks will not be added from my side.

P.S. your English is fine, don't worry about it.
