### ISSUE TITLE
Performance issues when using irrigation system

### ISSUE THREAD

**Issue by xtremeqg** [InfinityRaider/AgriCraft#436]
The wooden irrigation channel used in average quantities (say 30-50 connected channels) when partially filled with water causes considerable drain on CPU resources. FPS dropped from 45 to 12 simply having them loaded in the world, they do not need to be visible. Performance returned to normal levels by either leaving them empty or removing them.

**Comment by InfinityRaider** [comment]
What version?

**Comment by Armigus** [comment]
I'm having bad lag spikes in my agricraft farmng area also.  Several stacks of channels and quite a few sprinklers.  The performance hit goes away when I'm far enough away.  The area is virtually unplayable (2-3 FPS).  Normal isn't the best either (9-10 FPS) but manageable.

Current version for now (1.4.3).

**Comment by InfinityRaider** [comment]
Did some testing myself: 4 3x3x3 tanks feeding into one 5x10x5 tank. This tank then feeds 4 irrigation systems which irrigate 16 farms, FPS is stable around 60, with occasional dips of 5~10fps:
http://puu.sh/l4vUt/905d905678.jpg
http://puu.sh/l4vX6/d36411a59f.jpg
http://puu.sh/l4vYe/a5ad0bdd6f.jpg
http://puu.sh/l4w05/4a223248f3.jpg
http://puu.sh/l4w14/a00f534389.jpg
http://puu.sh/l4w20/59f5502897.jpg
http://puu.sh/l4w3i/7601e34f72.jpg

Ironically the largest performance impacts comes from the block updates caused by crops growing, which forces chunks to re-render. If you machine can't handle it I suggest reducing the size of your farms. 10/10 crops really give a huge yield as it is.

**Comment by xtremeqg** [comment]
At the time I did not have any crops that were not fully grown so it could not have been block updates. I'm using AgriCraft-1.7.10-1.4.3, same as @Armigus.

**Comment by xtremeqg** [comment]
Strange, making a minimal test build of the setup I was using doesn't drop FPS as badly as reported (40 to 24ish). Perhaps the crops were performing block updates even while fully grown?

![screenshot from 2015-11-04 19 49 49](https://cloud.githubusercontent.com/assets/15368271/10946929/a51a5774-832d-11e5-82fb-b22a20d15140.png)

**Comment by InfinityRaider** [comment]
still quite a huge fps drop for just that setup though. can you remove the bc pipes (so its just the irrigation system) and see how that impacts fps? It might be interaction between pipes and tanks which Im handling wrongly.

**Comment by thephoenixlodge** [comment]
The issue  there would be the interaction between pipes and tank, but not the agricraft tanks - the mariculture one. There is a known bug where BC fluid pipes connected to Mariculture tanks causes an FPS drop

**Comment by InfinityRaider** [comment]
Didn't know this. Thanks for the headsup.

**Comment by Shirkit** [comment]
Well, to be fair, I've got an i7 @ 3.2GHZ with a GTX750 and by simply turning on 16 sprinklers, FPS dropped from 120ish to around 40, even if the tiles below are just plain grass. Can't use the irrigation system.
