### ISSUE TITLE
Seed storage bug

### ISSUE THREAD

**Issue by P3pp3rF1y** [InfinityRaider/AgriCraft#440]
Seed storage allows for skipping seed generations. If you pipe in an empty seed storage (used extra utils transfer node) it won't show any seed at all, but if you then click in a seed (any kind of seed) it will have attributes of the seed that you piped in.

Version: AgriCraft-1.7.10-1.4.1-1.7.10

**Comment by InfinityRaider** [comment]
Weird, i'll have a look at it, thanks for reporting.

**Comment by InfinityRaider** [comment]
Was able to reproduce and tracked down why this was happening.
This is due to how the seed storage internally handles slots, if you try a hopper, you'll see that it is even quirkier: stacks just get deleted.
To fix this I made the storage ISidedInventory instead of just IInventory and only allow extracting. Automatic input is disabled.
