### ISSUE TITLE
disappearing crop sticks

### ISSUE THREAD

**Issue by SwiftSlide** [InfinityRaider/AgriCraft#558]
the crop sticks are glitching out. one time their invisible and then next tiume theur not. and than half of them are invisible.
i have fastcraft, better fps and optifine installed. maybe some rendering issue with those mods?
![2016-02-07_23 23 59](https://cloud.githubusercontent.com/assets/17113940/12875802/fef7b9bc-cdf1-11e5-8a4d-476266d13a8d.png)
![2016-02-07_23 24 03](https://cloud.githubusercontent.com/assets/17113940/12875803/ff072762-cdf1-11e5-9c94-43d83cb704c6.png)
![2016-02-07_23 24 18](https://cloud.githubusercontent.com/assets/17113940/12875801/fef5a3a2-cdf1-11e5-94d0-240660851852.png)

**Comment by InfinityRaider** [comment]
Some Optifine settings don't like the fact that I'm using my own Tessellator class isntead of the MC tessellator. There's nothing I can do about it.

**Comment by Timeslice42** [comment]
The obvious solution would be to stop using your own tessellator, as agricraft used to work with optifine just fine. Or better yet, use the MC tessellator when optifine is detected. We can live with the odd shadows when it means we don't have to give up multi-core chunk loading.

Can't wait for 1.9's built in multicore chunk loading...

**Comment by InfinityRaider** [comment]
In 1.7 my tessellator is just the MC tessellator wrapped up, the transformations are handled by me, but the vertices are still drawn with the mc Tessellator.

**Comment by InfinityRaider** [comment]
Also, the MC Tessellator does not handle rotations/scaling, which mine does, so using the mc Tessellator would require a lot of code adaptations which I do not want to do.

**Comment by Timeslice42** [comment]
So what exactly changed? Was it a change in AC or Optifine? I know this problem didn't exist when I was working with you last year to get my modpack done (all of those config options I asked for, etc.).

**Comment by InfinityRaider** [comment]
The only thing what changed in AgriCraft is a different render setting (to switch from ISBRH to TESR), but it is off by default.

**Comment by skaviouz** [comment]
I understand this issue is 8 years old and there will be no further updates, but I thought I would write a workaround for people. As it wasn't clearly written anywhere like other workaround like when you require to turn "anisotropic filter" off for a mod like Quadrum.

## Work Around:

When you have Optifine installed (Example, 1.7.10_HD_U_E7)
Options > Video Settings > Performance > Fast Renderer: Off

IIUC by telling Optifine this, your client will use the default MC shading and rendering. Even with this one setting turned off, Optifine still gives plenty of other speed ups, so it's worth not disabling the entire mod...
