### ISSUE TITLE
MineFactory Reloaded Fertilizer Issue

### ISSUE THREAD

**Issue by Zoidey** [InfinityRaider/AgriCraft#583]
Not sure if anyone has noticed or posted this issue (that I could see or find) but here I go anyway.

A friend and myself have noticed how the MFR Fertilizers don't seem to work. You put the MFR fertilizer in it or bone meal (when you enable it in the config) and nothing happens. It's full of fertilizer and power but just sits there doing nothing. It seems to be an issue with Agricraft as I removed the Agricraft mod and run a singleplayer map and it worked once Agricraft was removed. Maybe it's the crop sticks that are blocking the MFR Fertilizer from seeing the crops (kinda like the issue with the Railcraft invisible blocks). Any fix for this to have them work together (The MFR Fertilizer and Agricraft).

Using AgriCraft-1.7.10-1.4.0-1.7.10 and MineFactoryReloaded-[1.7.10]2.8.0-104 in the Agrarian Skies 2 mod pack.

All seeds seem to be effected vanilla, pams, agricraft.

**Comment by Storm-Engineer** [comment]
I also have this issue with Infinity Evolved modpack (It does have Agricraft but I'm trying it with planted seeds not Cropsticks). Fertilizer has both Forestry Fertilizer and Industrial Fertilizer in it, and does nothing. I even tried that the fertilizers work on the crop if used manually.

**Comment by predakanga** [comment]
To support MFR Fertilizers, AgriCraft would have to implement powercrystals.minefactoryreloaded.api.IFactoryFertilizable and register it via IMC - I can provide a pull request for this if need be, but the bigger question is whether or not this is intentional.

It's trivial to support CropPlant's canBonemeal condition for this, so I'd suggest allowing it with a config option to disable

**Comment by Storm-Engineer** [comment]
It's not only Agricraft, fertilizer block doesn't work with Immersive Engineering's Industrial Hemp either because the Hemp does not support the MFR fertilizer, only other other fertilizer which in turn is not supported by MFR itself, as it is loaded in the Fertilizer block but it does not use it.

Both MFR should support the Fertilizer items from other mods, and Agricraft and Immersive Engineering should support MFR fertilizer.
