### ISSUE TITLE
[1.2.2] custom soils can be defined, but not used

### ISSUE THREAD

**Issue by Belgabor** [InfinityRaider/AgriCraft#64]
You can define a custom soil in SoilWhitelist.txt, but trying to use it in CustomCrops.txt leads to an error:

    [AgriCraft]: Error when adding custom crop: Invalid soil: soil should be null, minecraft:sand, minecraft:soul_sand or minecraft:mycelium (line: chrysalis,DCsAppleMilk:defeatedcrow.condensedMilk:5,minecraft:glass,null,3,1,A magical flower with fragile crystalline stem and leaves)

(Yes, glass is defined in SoilWhitelist.txt)

**Comment by InfinityRaider** [comment]
I changed the way the soil whitelist works, the soil whitelist is just to whitelist other mod's farmland (forestry humus, magical crops' soil, ...)
The soil in the custom crops config works like this:
If you set it to null (dont specify a specific soil), the crop can be planted on vanilla farmland and every soil you whitelisted. If you specify a soil, it will only be able to be planted, grow and mutate on that soil. For now only sand, soul sand and mycelium are supported (because now crops can only be set on those) but I will soon add the option to specify any block.

**Comment by Belgabor** [comment]
AH! I misinterpreted that!

**Comment by InfinityRaider** [comment]
No problem, it happens
