### ISSUE TITLE
1.10 Issues

### ISSUE THREAD

**Issue by RlonRyan** [InfinityRaider/AgriCraft#679]
Bugs:
- [x] Config has unused options.
- [x] Crops Are Solid?
- [x] Clipper does not update the crop.
- [x] Renderer Issues
- [x] Add missing getActualState();
- [x] Seed analyzer rendering issues. (Crash when out of chunk, Disappears randomly). (This may or may not be resolved...).
- [x] Gardening Trowel does not cause an update, leaving ghost plants.
- [x] Core Items come after all the custom wood variants, should come before.
- [x] Grates Ignore Rotation
- [x] Tanks + Seed Analyzer Only Render in SMP
- [x] Journal Items Messing Up Alpha.
- [x] Crossbreeding Not Working.
- [x] WAILA Integration Borked.
- [x] Base Blocks not working.
- [x] Plant textures switching in multiplayer.
- [x] Item rotations no longer working.
- [x] JSON Plants Incomplete -> (Not really our problem anymore... This is all up to the pack makers.)
- [x] Mutations Nonfunctional
- [x] Crop Age BlockState is Bugged
- [x] Journal Doesn't Work In Hand
- [x] Nuggets Not Rendering
- [x] Items Have Comical Sizes & Rotations
- [x] JEI Integration Borked
- [x] Weeds Not Rendering

**Comment by Speiger** [comment]
@RlonRyan i can help you with Crop Age BlockState... Really easy bugfix only thing you have to do is adjusting it to your mod...
Here is the way you can fix it:
Forge is mapping every block state that you provide as metadata. (Overriding each other based on what metadata you provide) So you can have only 16 BlockStates and the rest either has to be IUnlistedProperty or do not use BlockStates for that stuff either...
Now my way does not use UnlistedProperty at all its allowing you to add as much IProperties as you want (but if you get to high (10k BlockState Area) it will cause Ram Issues).
Simply add a CustomBlockStateContainer that will create blockStates as normal (copy/paste code) after the block states are generated (in the constructor) it will pick the default state and ask the Block which states are metadata and put these instead of all BlockStates. The BlockStates are not removed they are just invisible to Minecraft and you show what you want to provide while still able to use Properties in it.
I call these RenderStates & they are json compatible do not need to write a custom loader or something. But you have to write a CustomBlockState mapper for the ModelBakery so it will see these RenderStates...

**Comment by InfinityRaider** [comment]
Seems I was a bit overzealous with closign issues, my bad

**Comment by Xiaminou** [comment]
I opened a couple of issues because I'm not sure if all those bugs are supposed to be fixed in the version released on curseforge.
In retrospect I should probably have asked first.
