### ISSUE TITLE
Scrolling too Fast in JEI past Agricraft items crashes the game

### ISSUE THREAD

**Issue by Joshwoo70** [InfinityRaider/AgriCraft#808]
Gists :
https://gist.github.com/Joshwoo70/5daf6c4e3fa994395b61e403a97bb7bd

**Comment by RlonRyan** [comment]
This might not be easy to fix, since the mod depends on just-in-time model generation, wherein the models aren't actually created until after the json files are received from the server and generated at first render request. The rapid scrolling of JEI might overtax the system to the point of failure.

**Comment by RlonRyan** [comment]
Actually, it appears that you have allocated forge too little memory to run. The reason it didn't show up until the AgriCraft blocks was because we use lazy loading to speed up boot times.

**Comment by TehNut** [comment]
`-Xms512m -Xmx1024m`

Yeah you definitely need more than 1Gb. Especially with... what is that? 150 mods or so?

**Comment by RlonRyan** [comment]
Lol... I didn't realize that the memory allocation was that low... Even more impressive that it actually launched in the first place.

**Comment by Joshwoo70** [comment]
ah i see... dammit multimc XD jeeps settig my memory sometimes a bit too low...

**Comment by Joshwoo70** [comment]
also probably why i loaded is more likely thanks to foamfix...
